review:
  from_address: ndliblis@nd.edu
  subject_text: Review of Event Needed
  body_text: This is a test email for review
  template_file: notice.text.html.erb
event_planned:
  from_address: ndliblis@nd.edu
  subject_text: "Event #{event_id} Planned"
  body_text: "An event #{event_link} is planned, and ready for Master video records.\r\n#{comment}"
  template_file: notice.text.html.erb
event_video_captured:
  from_address: ndliblis@nd.edu
  subject_text: "Event #{event_id} Master Video #{master_id} Available"
  body_text: "An event #{event_link} has been captured and the Master Video #{master_link} is available for derivatives.\r\n#{comment}"
  template_file: notice.text.html.erb
event_updated:
  from_address: ndliblis@nd.edu
  subject_text: "Event Updated #{event_id]}"
  body_text: "An existing event has been updated.  Please follow this #{event_link} to review any changes that may be related to Master and/or Derivative Videos.\r\n#{comment}"
  template_file: notice.text.html.erb
master_video_updated:
  from_address: ndliblis@nd.edu
  subject_text: "Master Video #{master_link} for Event #{event_link} has been Updated"
  body_text: "An existing master video record has been updated.  Please follow this #{master_link} to review any changes that may be related to Derivative Videos.\r\n#{comment}"
  template_file: notice.text.html.erb