production:
  source:
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@salt-prod.stanford.edu:8080/fedora
    solr:
      url: http://salt-prod.stanford.edu:8080/solr
  destination:
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@salt-dev.stanford.edu:8080/fedora
    solr:
      url: http://salt-dev.stanford.edu:8080/solr
staging: &TEST
  source:
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@salt-prod.stanford.edu:8080/fedora
    solr:
      url: http://salt-prod.stanford.edu:8080/solr
  destination:  
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@salt-dev.stanford.edu:8080/fedora
    solr:
      url: http://salt-dev.stanford.edu:8080/solr
development: &DEV
  source:
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@localhost:8080/fedora
    solr:
      url: http://localhost:8080/solr
  destination:
    fedora:
      url: http://fedoraAdmin:fedoraAdmin@salt-dev.stanford.edu:8080/fedora
    solr:
      url: http://salt-dev.stanford.edu:8080/solr
dev_cached:
  <<: *DEV
test:
  <<: *TEST
cucumber:
  <<: *TEST
